/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejemplos;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author maraloed
 */
public class LecturaEscrituraBinaria extends javax.swing.JFrame {

    /**
     * Creates new form LecturaEscrituraBinaria
     */
    static JFileChooser jfc;
    static File f;
    static FileOutputStream fos = null;
    static BufferedOutputStream br = null;
    static DataOutputStream dos = null;
    static Random rndm = new Random();

    public LecturaEscrituraBinaria() {
        initComponents();
        setFrame();
    }

    void setFrame() {
        setTitle("LECTURA ESCTIRURA");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    File seleccionFichero(File fichero) {
        jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        f = null;
        int respuesta = jfc.showOpenDialog(null);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
        }
        return f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ElegirFichero = new javax.swing.JButton();
        EscribirFichero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ElegirFichero.setText("Elegir Fichero");
        ElegirFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirFicheroActionPerformed(evt);
            }
        });

        EscribirFichero.setText("Escribir fichero");
        EscribirFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirFicheroActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EscribirFichero)
                    .addComponent(ElegirFichero))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ElegirFichero)
                        .addGap(67, 67, 67)
                        .addComponent(EscribirFichero)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElegirFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirFicheroActionPerformed
        seleccionFichero(f);

    }//GEN-LAST:event_ElegirFicheroActionPerformed

    private void EscribirFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirFicheroActionPerformed

        fos = null;
        br=null;
        dos=null;
        
        try {
            //Grabamos en el fichero 100 numeros aleatorios
            seleccionFichero(f);
            if (f == null) {
                return;
            }
            fos = new FileOutputStream(f);
            BufferedOutputStream br = new BufferedOutputStream(fos);
            DataOutputStream dos = new DataOutputStream(fos);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LecturaEscrituraBinaria.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(LecturaEscrituraBinaria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        double aleatorio = 0.0;
        for (double i = 0; i <= 100; i++) {

            try {
                dos.writeDouble(aleatorio);
            } catch (IOException ex) {
                Logger.getLogger(LecturaEscrituraBinaria.class.getName()).log(Level.SEVERE, null, ex);
            }

        jTextArea1.setText(String.valueOf(aleatorio));
        }


    }//GEN-LAST:event_EscribirFicheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturaEscrituraBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturaEscrituraBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturaEscrituraBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturaEscrituraBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturaEscrituraBinaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ElegirFichero;
    private javax.swing.JButton EscribirFichero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
