package EjerciciosSergio;

import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Ejercicio05_GUIFincas extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio06_Finca
     */
    //AñadirFinca
    static FileOutputStream fos;
    static BufferedOutputStream bos;
    static DataOutputStream dos;
    static ArrayList<Ejercicio05_Fincas> listaFincas = new ArrayList<>();
    static File archivoFincas;
    static Ejercicio05_Fincas datosFincas = new Ejercicio05_Fincas();

    public Ejercicio05_GUIFincas() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        setTitle("El Ejercicio");
        setLocationRelativeTo(null);
        setSize(500, 300);
        setResizable(false);
    }

    void agregarFinca() {

        String nombreFinca = "";

        do {

            nombreFinca = JOptionPane.showInputDialog(null,
                    "Introduce un nombre para ña finca");

            if (nombreFinca == null || nombreFinca.isEmpty()) {
                JOptionPane.showMessageDialog(null,
                        "No has introducido nada, vuelve a intentarlo");
                return;
            }
        } while (nombreFinca.isEmpty());

        archivoFincas = new File("C:\\Users\\maraloed\\Desktop\\Fincas\\fincas.pal");

        if (!archivoFincas.exists()) {
            try {
                archivoFincas.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Ejercicio05_GUIFincas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            listaFincas.add());

            fos = new FileOutputStream(archivoFincas, true);
            bos = new BufferedOutputStream(fos);
            dos = new DataOutputStream(fos);

            dos.writeUTF(String.valueOf(listaFincas));

            dos.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ejercicio05_GUIFincas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ejercicio05_GUIFincas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void borrarFinca() {

        String idExistente =JOptionPane.showInputDialog(null,
                         "Introduce un id");
        
        int datos = datosFincas.getNumeroIdentificacion();
        
        datos=Integer.parseInt(idExistente);
            
            for(Ejercicio05_Fincas ids : listaFincas){
                
                if (ids.equals(idExistente)){
                    
                }
            }
            
        
    }

    void verFincas() {
        datosFinca.setText(String.valueOf(datosFincas.toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNormal = new javax.swing.JPanel();
        datosFinca = new javax.swing.JTextField();
        anadirFinca = new javax.swing.JButton();
        borrarFinca = new javax.swing.JButton();
        verFinca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        datosFinca.setEditable(false);
        datosFinca.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        datosFinca.setToolTipText("");
        datosFinca.setAlignmentX(0.0F);
        datosFinca.setAlignmentY(0.0F);
        datosFinca.setBorder(javax.swing.BorderFactory.createTitledBorder("FINCAS MANOLO"));
        datosFinca.setPreferredSize(new java.awt.Dimension(0, 0));

        anadirFinca.setText("Añadir Finca");
        anadirFinca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anadirFincaMouseClicked(evt);
            }
        });

        borrarFinca.setText("Borrar Finca");
        borrarFinca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarFincaMouseClicked(evt);
            }
        });

        verFinca.setText("Ver Fincas");
        verFinca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verFincaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelNormalLayout = new javax.swing.GroupLayout(PanelNormal);
        PanelNormal.setLayout(PanelNormalLayout);
        PanelNormalLayout.setHorizontalGroup(
            PanelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNormalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verFinca)
                    .addComponent(borrarFinca)
                    .addComponent(anadirFinca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(datosFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelNormalLayout.setVerticalGroup(
            PanelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNormalLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(anadirFinca)
                .addGap(33, 33, 33)
                .addComponent(borrarFinca)
                .addGap(33, 33, 33)
                .addComponent(verFinca)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(PanelNormalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(datosFinca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirFincaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadirFincaMouseClicked
        agregarFinca();
    }//GEN-LAST:event_anadirFincaMouseClicked

    private void borrarFincaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarFincaMouseClicked
        borrarFinca();
    }//GEN-LAST:event_borrarFincaMouseClicked

    private void verFincaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFincaMouseClicked
        verFincas();
    }//GEN-LAST:event_verFincaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ejercicio05_GUIFincas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNormal;
    private javax.swing.JButton anadirFinca;
    private javax.swing.JButton borrarFinca;
    private javax.swing.JTextField datosFinca;
    private javax.swing.JButton verFinca;
    // End of variables declaration//GEN-END:variables
}
