/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EjerciciosSergio;

/**
 *
 * @author Eduardo
 */
public class Ejercicio05_GUIFincas extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio06_Finca
     */
    public Ejercicio05_GUIFincas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNormal = new javax.swing.JPanel();
        datosFinca = new javax.swing.JTextField();
        anadirFinca = new javax.swing.JButton();
        borrarFinca = new javax.swing.JButton();
        verFinca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        datosFinca.setBorder(javax.swing.BorderFactory.createTitledBorder("FINCAS MANOLO"));

        anadirFinca.setText("Añadir Finca");

        borrarFinca.setText("Borrar Finca");

        verFinca.setText("Ver Fincas");

        javax.swing.GroupLayout PanelNormalLayout = new javax.swing.GroupLayout(PanelNormal);
        PanelNormal.setLayout(PanelNormalLayout);
        PanelNormalLayout.setHorizontalGroup(
            PanelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNormalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNormalLayout.createSequentialGroup()
                        .addGroup(PanelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anadirFinca)
                            .addComponent(borrarFinca))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(verFinca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(datosFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelNormalLayout.setVerticalGroup(
            PanelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNormalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(datosFinca)
                .addContainerGap())
            .addGroup(PanelNormalLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(anadirFinca)
                .addGap(33, 33, 33)
                .addComponent(borrarFinca)
                .addGap(33, 33, 33)
                .addComponent(verFinca)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05_GUIFincas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio05_GUIFincas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNormal;
    private javax.swing.JButton anadirFinca;
    private javax.swing.JButton borrarFinca;
    private javax.swing.JTextField datosFinca;
    private javax.swing.JButton verFinca;
    // End of variables declaration//GEN-END:variables
}
