/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejemplos;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SpringLayout;
/**
 *
 * @author maraloed
 */
public class TiposLayouts extends javax.swing.JFrame {

    int contadorBotones=1;
    
    /**
     * Creates new form TiposLayouts
     */
    public TiposLayouts() {
        initComponents();
        setFrame();
        setFlowLayout();
        setGridBag();
        setBorderLayout();
        setBoxLayout();
    }
    
   private void setFrame(){
        setTitle("Administracion de diseño");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
    }
   
   private void setFlowLayout(){
       
       for (int i = 1; i <= 10; i++) {
           
           panelFlow.add(new JButton(String.valueOf(i)));
           
       }
   }
       
       private void setGridBag(){  
       
   }
       
       private void setBorderLayout(){
           
           
           
       }
       
       private void setBoxLayout(){
           for (int i = 0; i < 10; i++) {
               
               panelBox.add(new JButton(String.valueOf(i)));
               
           }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFlow = new javax.swing.JPanel();
        panelGridBag = new javax.swing.JPanel();
        panelBox = new javax.swing.JPanel();
        panelGridL = new javax.swing.JPanel();
        panelBorder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFlow.setBackground(new java.awt.Color(102, 255, 102));
        panelFlow.setBorder(javax.swing.BorderFactory.createTitledBorder("FlowLayout"));
        getContentPane().add(panelFlow, java.awt.BorderLayout.PAGE_START);

        panelGridBag.setBackground(new java.awt.Color(255, 102, 204));
        panelGridBag.setBorder(javax.swing.BorderFactory.createTitledBorder("GrifidLayout"));
        panelGridBag.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(panelGridBag, java.awt.BorderLayout.LINE_START);

        panelBox.setBackground(new java.awt.Color(204, 0, 255));
        panelBox.setBorder(javax.swing.BorderFactory.createTitledBorder("BoxLayout"));
        panelBox.setLayout(new javax.swing.BoxLayout(panelBox, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelBox, java.awt.BorderLayout.LINE_END);

        panelGridL.setBackground(new java.awt.Color(204, 255, 204));
        panelGridL.setBorder(javax.swing.BorderFactory.createTitledBorder("GridLayout"));
        panelGridL.setLayout(new java.awt.GridLayout());
        getContentPane().add(panelGridL, java.awt.BorderLayout.PAGE_END);

        panelBorder.setBackground(new java.awt.Color(255, 255, 51));
        panelBorder.setBorder(javax.swing.BorderFactory.createTitledBorder("BorderLayout"));
        panelBorder.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelBorder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiposLayouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiposLayouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiposLayouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiposLayouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TiposLayouts().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelBorder;
    private javax.swing.JPanel panelBox;
    private javax.swing.JPanel panelFlow;
    private javax.swing.JPanel panelGridBag;
    private javax.swing.JPanel panelGridL;
    // End of variables declaration//GEN-END:variables
}
